### ISSUE TITLE
Main file gets included once

### ISSUE THREAD

**Issue by Volker-Weissmann** [tgflynn/IncludeGuards#1]
```
$ cat a.jl 
using IncludeGuards
@includeonce "b.jl"
func()
$ cat b.jl 
@includeonce "a.jl"
function func()
end
$ julia a.jl 
ERROR: LoadError: LoadError: LoadError: UndefVarError: func not defined
Stacktrace:
 [1] top-level scope
   @ ~/Sync/DatenVolker/small/IT/my blogposts/julia_error_msg/a.jl:3
 [2] top-level scope
   @ ~/Sync/DatenVolker/small/IT/my blogposts/julia_error_msg/b.jl:1
 [3] top-level scope
   @ ~/Sync/DatenVolker/small/IT/my blogposts/julia_error_msg/a.jl:2
in expression starting at /home/volker/Sync/DatenVolker/small/IT/my blogposts/julia_error_msg/a.jl:3
in expression starting at /home/volker/Sync/DatenVolker/small/IT/my blogposts/julia_error_msg/b.jl:1
in expression starting at /home/volker/Sync/DatenVolker/small/IT/my blogposts/julia_error_msg/a.jl:2
```

**Comment by tgflynn** [comment]
That is the expected behavior for your example.

When you run a.jl the first thing it does is include b.jl, which then includes a.jl.  IncludeGuards does not prevent that inclusion because it is the first time a.jl has been included by @includeonce.  If you did this with include instead you would get an infinite inclusion loop and julia would hang.  IncludeGuards does prevent the infinite loop but the next thing a.jl does is try to call func(), which hasn't been defined yet at the place where it got included.

**Comment by Volker-Weissmann** [comment]
Yeah, that's the part I know.

But can this be prevented?

**Comment by tgflynn** [comment]
Not by this package, it's not designed to prevent that, only to provide an include guard mechanism similar to what is used in C/C++ and your example wouldn't work in C either.

Functions always need to be defined before they are called.  I would say that if your code isn't ensuring that then it's broken.

Why would you want to do something like this ?  Can you give a more realistic example of where this would be useful ?

**Comment by Volker-Weissmann** [comment]
My real world code is as follows:

1. I have about 20 julia files
2. I have about 7 julia files that I run with `julia filename.jl` or vscode shift+enter.
3. Code is badly sorted distributed on those 20 files. Therefore, @includeonce nearly every other file in every file.

The exakt situation was:

I wanted to add "gaspard_robustness_omega(bc)" to https://gitlab.com/volkerweissmann/sm_with_julia/-/tree/d7f51a7077a2279abee5101340d2a574063b58ed/Br%C3%BCsselator/attract.jl , then run the code, but it told me that `calc_M` is undefined. Creating https://gitlab.com/volkerweissmann/sm_with_julia/-/tree/d7f51a7077a2279abee5101340d2a574063b58ed/Br%C3%BCsselator/wrap.jl  was my solution.

Is it possible to make the error message nicer.
It took me quite a while to find it.

**Comment by tgflynn** [comment]
All I can suggest is that you reorganize your code to eliminate cyclic dependencies.  Having every file include every other file is far from a best practice.

As for the error message, that comes from julia and has no direct connection with this package.

**Comment by Volker-Weissmann** [comment]
Ok.
